<?xml version="1.0" encoding="utf-8"?><Database Name="GestioneGuasti-2019" Class="GestioneGuastiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=gestioneguasti.database.windows.net;Initial Catalog=GestioneGuasti-2019;Persist Security Info=True;User ID=matteo" SettingsObjectName="FailuresManagement.Properties.Settings" SettingsPropertyName="GestioneGuasti_2019ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Progettisti" Member="Progettisti">
    <Type Name="Progettisti">
      <Column Name="Codice" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LuogoNascita" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Residenza" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Stipendio" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Progettisti_Interessi" Member="Interessi" ThisKey="Codice" OtherKey="CodiceProgettista" Type="Interessi" />
    </Type>
  </Table>
  <Table Name="dbo.TopPNC" Member="TopPNC">
    <Type Name="TopPNC">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopComponentCode" Member="TopComponentCode">
    <Type Name="TopComponentCode">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="ComponentCode" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="NomeComponente" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AvgTime" Member="AvgTime">
    <Type Name="AvgTime">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceTipo" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="NomeTipo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TempoMedioRiparazione" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopCostSpareParts" Member="TopCostSpareParts">
    <Type Name="TopCostSpareParts">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="DataRichiestaIntervento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CostoTotale" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopSpareParts" Member="TopSpareParts">
    <Type Name="TopSpareParts">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="Codice" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CostoAcquisto" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
      <Column Name="CostoInstallazione" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TTFInstallation" Member="TTFInstallation">
    <Type Name="TTFInstallation">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" CanBeNull="false" />
      <Column Name="SNC" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceGaranzia" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="Modello" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="[TTF (giorni)]" Member="TTF_in_giorni" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TTFPurchase" Member="TTFPurchase">
    <Type Name="TTFPurchase">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" CanBeNull="false" />
      <Column Name="SNC" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceGaranzia" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="Modello" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="[TTF (giorni)]" Member="TTF_in_giorni" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Interessi" Member="Interessi">
    <Type Name="Interessi">
      <Column Name="CodiceCategoria" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodiceProgettista" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Progettisti_Interessi" Member="Progettisti" ThisKey="CodiceProgettista" OtherKey="Codice" Type="Progettisti" IsForeignKey="true" />
      <Association Name="Categorie_Interessi" Member="Categorie" ThisKey="CodiceCategoria" OtherKey="Codice" Type="Categorie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Guasti" Member="Guasti">
    <Type Name="Guasti">
      <Column Name="NumeroTelefonoCliente" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataRichiestaIntervento" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SNC" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DescrizioneCliente" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescrizioneTecnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="ComponentCode" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="CodiceTipoDifetto" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Association Name="Prodotti_Guasti" Member="Prodotti" ThisKey="PNC,SNC" OtherKey="PNC,SNC" Type="Prodotti" IsForeignKey="true" />
      <Association Name="Interventi_Guasti" Member="Interventi" ThisKey="NumeroTelefonoCliente,DataRichiestaIntervento" OtherKey="NumeroTelefonoCliente,DataRichiesta" Type="Interventi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Operatori" Member="Operatori">
    <Type Name="Operatori">
      <Column Name="Codice" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LuogoNascita" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Residenza" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Stipendio" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="CodiceNazionaleCentro" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="NazioneCentro" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="Operatori_Interventi" Member="Interventi" ThisKey="Codice" OtherKey="CodiceOperatore" Type="Interventi" />
      <Association Name="Centri_Assistenza_Operatori" Member="Centri_Assistenza" ThisKey="CodiceNazionaleCentro,NazioneCentro" OtherKey="CodiceNazionale,Nazione" Type="Centri_Assistenza" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tecnici" Member="Tecnici">
    <Type Name="Tecnici">
      <Column Name="Codice" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LuogoNascita" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Residenza" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Stipendio" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DipendenteInterno" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CodiceNazionaleCentro" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="NazioneCentro" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="Tecnici_Interventi" Member="Interventi" ThisKey="Codice" OtherKey="CodiceTecnico" Type="Interventi" />
      <Association Name="Centri_Assistenza_Tecnici" Member="Centri_Assistenza" ThisKey="CodiceNazionaleCentro,NazioneCentro" OtherKey="CodiceNazionale,Nazione" Type="Centri_Assistenza" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewInterventions" Member="NewInterventions">
    <Type Name="NewInterventions">
      <Column Name="NumeroTelefonoCliente" Member="Numero_di_telefono_cliente" Storage="_NumeroTelefonoCliente" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DataRichiesta" Member="Data_richiesta" Storage="_DataRichiesta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Prodotti" Member="Prodotti">
    <Type Name="Prodotti">
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SNC" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Modello" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DataAcquisto" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DataInstallazione" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CodiceGaranzia" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="CodiceCategoria" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Association Name="Prodotti_Guasti" Member="Guasti" ThisKey="PNC,SNC" OtherKey="PNC,SNC" Type="Guasti" />
      <Association Name="Categorie_Prodotti" Member="Categorie" ThisKey="CodiceCategoria" OtherKey="Codice" Type="Categorie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorie" Member="Categorie">
    <Type Name="Categorie">
      <Column Name="Codice" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Categorie_Interessi" Member="Interessi" ThisKey="Codice" OtherKey="CodiceCategoria" Type="Interessi" />
      <Association Name="Categorie_Prodotti" Member="Prodotti" ThisKey="Codice" OtherKey="CodiceCategoria" Type="Prodotti" />
    </Type>
  </Table>
  <Table Name="dbo.CentersIntervAvg" Member="CentersIntervAvg">
    <Type Name="CentersIntervAvg">
      <Column Name="CodiceNazionale" Member="Codice_nazionale" Storage="_CodiceNazionale" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nazione" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Sede" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="AreaCompetenza" Member="Area_di_competenza" Storage="_AreaCompetenza" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TempoMedioRiparazione" Member="Tempo_di_riparazione_medio" Storage="_TempoMedioRiparazione" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OperatorsIntervCount" Member="OperatorsIntervCount">
    <Type Name="OperatorsIntervCount">
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TechniciansIntervCount" Member="TechniciansIntervCount">
    <Type Name="TechniciansIntervCount">
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TechniciansIntervAvg" Member="TechniciansIntervAvg">
    <Type Name="TechniciansIntervAvg">
      <Column Name="CF" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TempoMedioImpiegato" Member="Tempo_impiegato_in_media" Storage="_TempoMedioImpiegato" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clienti" Member="Clienti">
    <Type Name="Clienti">
      <Column Name="NumeroTelefono" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Clienti_Interventi" Member="Interventi" ThisKey="NumeroTelefono" OtherKey="NumeroTelefonoCliente" Type="Interventi" />
    </Type>
  </Table>
  <Table Name="dbo.TopZones" Member="TopZones">
    <Type Name="TopZones">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="Zona" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[#]" Member="Numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Interventi" Member="Interventi">
    <Type Name="Interventi">
      <Column Name="NumeroTelefonoCliente" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataRichiesta" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Stato" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DataVisita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TempoImpiegato" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="Zona" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceOperatore" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceTecnico" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Association Name="Interventi_Guasti" Member="Guasti" ThisKey="NumeroTelefonoCliente,DataRichiesta" OtherKey="NumeroTelefonoCliente,DataRichiestaIntervento" Type="Guasti" />
      <Association Name="Operatori_Interventi" Member="Operatori" ThisKey="CodiceOperatore" OtherKey="Codice" Type="Operatori" IsForeignKey="true" />
      <Association Name="Tecnici_Interventi" Member="Tecnici" ThisKey="CodiceTecnico" OtherKey="Codice" Type="Tecnici" IsForeignKey="true" />
      <Association Name="Clienti_Interventi" Member="Clienti" ThisKey="NumeroTelefonoCliente" OtherKey="NumeroTelefono" Type="Clienti" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Centri_Assistenza" Member="Centri_Assistenza">
    <Type Name="Centri_Assistenza">
      <Column Name="CodiceNazionale" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nazione" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sede" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="AreaCompetenza" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="Centri_Assistenza_Operatori" Member="Operatori" ThisKey="CodiceNazionale,Nazione" OtherKey="CodiceNazionaleCentro,NazioneCentro" Type="Operatori" />
      <Association Name="Centri_Assistenza_Tecnici" Member="Tecnici" ThisKey="CodiceNazionale,Nazione" OtherKey="CodiceNazionaleCentro,NazioneCentro" Type="Tecnici" />
    </Type>
  </Table>
  <Table Name="dbo.AllFaults" Member="AllFaults">
    <Type Name="AllFaults">
      <Column Name="CategoriaProdotto" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="PNC" Type="System.Decimal" DbType="Decimal(11,0) NOT NULL" CanBeNull="false" />
      <Column Name="SNC" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="Modello" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DataRichiestaIntervento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataVisita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataAcquisto" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DataInstallazione" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Zona" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DescrizioneCliente" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescrizioneTecnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComponentCode" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="NomeComponente" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceTipoDifetto" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="NomeTipoDifetto" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceRicambio" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="NomeRicambio" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CostoAcquisto" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="CostoInstallazione" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
    </Type>
  </Table>
</Database>