#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FailuresManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestioneGuasti-2019")]
	public partial class GestioneGuastiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertProgettisti(Progettisti instance);
    partial void UpdateProgettisti(Progettisti instance);
    partial void DeleteProgettisti(Progettisti instance);
    partial void InsertInteressi(Interessi instance);
    partial void UpdateInteressi(Interessi instance);
    partial void DeleteInteressi(Interessi instance);
    partial void InsertGuasti(Guasti instance);
    partial void UpdateGuasti(Guasti instance);
    partial void DeleteGuasti(Guasti instance);
    #endregion
		
		public GestioneGuastiDataContext() : 
				base(global::FailuresManagement.Properties.Settings.Default.GestioneGuasti_2019ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AllFaults> AllFaults
		{
			get
			{
				return this.GetTable<AllFaults>();
			}
		}
		
		public System.Data.Linq.Table<Progettisti> Progettisti
		{
			get
			{
				return this.GetTable<Progettisti>();
			}
		}
		
		public System.Data.Linq.Table<TopPNC> TopPNC
		{
			get
			{
				return this.GetTable<TopPNC>();
			}
		}
		
		public System.Data.Linq.Table<TopComponentCode> TopComponentCode
		{
			get
			{
				return this.GetTable<TopComponentCode>();
			}
		}
		
		public System.Data.Linq.Table<AvgTime> AvgTime
		{
			get
			{
				return this.GetTable<AvgTime>();
			}
		}
		
		public System.Data.Linq.Table<TopCostSpareParts> TopCostSpareParts
		{
			get
			{
				return this.GetTable<TopCostSpareParts>();
			}
		}
		
		public System.Data.Linq.Table<TopNations> TopNations
		{
			get
			{
				return this.GetTable<TopNations>();
			}
		}
		
		public System.Data.Linq.Table<TopSpareParts> TopSpareParts
		{
			get
			{
				return this.GetTable<TopSpareParts>();
			}
		}
		
		public System.Data.Linq.Table<TTFInstallation> TTFInstallation
		{
			get
			{
				return this.GetTable<TTFInstallation>();
			}
		}
		
		public System.Data.Linq.Table<TTFPurchase> TTFPurchase
		{
			get
			{
				return this.GetTable<TTFPurchase>();
			}
		}
		
		public System.Data.Linq.Table<Interessi> Interessi
		{
			get
			{
				return this.GetTable<Interessi>();
			}
		}
		
		public System.Data.Linq.Table<Guasti> Guasti
		{
			get
			{
				return this.GetTable<Guasti>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AllFaults")]
	public partial class AllFaults
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private string _Modello;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private System.DateTime _DataVisita;
		
		private System.Nullable<System.DateTime> _DataAcquisto;
		
		private System.Nullable<System.DateTime> _DataInstallazione;
		
		private string _Nazione;
		
		private string _DescrizioneCliente;
		
		private string _DescrizioneTecnico;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private string _NomeComponente;
		
		private System.Nullable<decimal> _CodiceTipoDifetto;
		
		private string _NomeTipoDifetto;
		
		private System.Nullable<decimal> _CodiceRicambio;
		
		private string _NomeRicambio;
		
		private System.Nullable<decimal> _CostoAcquisto;
		
		private System.Nullable<decimal> _CostoInstallazione;
		
		public AllFaults()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL")]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					this._DataRichiestaIntervento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVisita", DbType="DateTime NOT NULL")]
		public System.DateTime DataVisita
		{
			get
			{
				return this._DataVisita;
			}
			set
			{
				if ((this._DataVisita != value))
				{
					this._DataVisita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAcquisto", DbType="Date")]
		public System.Nullable<System.DateTime> DataAcquisto
		{
			get
			{
				return this._DataAcquisto;
			}
			set
			{
				if ((this._DataAcquisto != value))
				{
					this._DataAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInstallazione", DbType="Date")]
		public System.Nullable<System.DateTime> DataInstallazione
		{
			get
			{
				return this._DataInstallazione;
			}
			set
			{
				if ((this._DataInstallazione != value))
				{
					this._DataInstallazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this._Nazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneCliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DescrizioneCliente
		{
			get
			{
				return this._DescrizioneCliente;
			}
			set
			{
				if ((this._DescrizioneCliente != value))
				{
					this._DescrizioneCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneTecnico", DbType="VarChar(100)")]
		public string DescrizioneTecnico
		{
			get
			{
				return this._DescrizioneTecnico;
			}
			set
			{
				if ((this._DescrizioneTecnico != value))
				{
					this._DescrizioneTecnico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeComponente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeComponente
		{
			get
			{
				return this._NomeComponente;
			}
			set
			{
				if ((this._NomeComponente != value))
				{
					this._NomeComponente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipoDifetto", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> CodiceTipoDifetto
		{
			get
			{
				return this._CodiceTipoDifetto;
			}
			set
			{
				if ((this._CodiceTipoDifetto != value))
				{
					this._CodiceTipoDifetto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeTipoDifetto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeTipoDifetto
		{
			get
			{
				return this._NomeTipoDifetto;
			}
			set
			{
				if ((this._NomeTipoDifetto != value))
				{
					this._NomeTipoDifetto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRicambio", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> CodiceRicambio
		{
			get
			{
				return this._CodiceRicambio;
			}
			set
			{
				if ((this._CodiceRicambio != value))
				{
					this._CodiceRicambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeRicambio", DbType="VarChar(20)")]
		public string NomeRicambio
		{
			get
			{
				return this._NomeRicambio;
			}
			set
			{
				if ((this._NomeRicambio != value))
				{
					this._NomeRicambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoAcquisto", DbType="SmallMoney")]
		public System.Nullable<decimal> CostoAcquisto
		{
			get
			{
				return this._CostoAcquisto;
			}
			set
			{
				if ((this._CostoAcquisto != value))
				{
					this._CostoAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoInstallazione", DbType="SmallMoney")]
		public System.Nullable<decimal> CostoInstallazione
		{
			get
			{
				return this._CostoInstallazione;
			}
			set
			{
				if ((this._CostoInstallazione != value))
				{
					this._CostoInstallazione = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Progettisti")]
	public partial class Progettisti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codice;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private string _LuogoNascita;
		
		private string _Residenza;
		
		private float _Stipendio;
		
		private EntitySet<Interessi> _Interessi;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceChanging(decimal value);
    partial void OnCodiceChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnLuogoNascitaChanging(string value);
    partial void OnLuogoNascitaChanged();
    partial void OnResidenzaChanging(string value);
    partial void OnResidenzaChanged();
    partial void OnStipendioChanging(float value);
    partial void OnStipendioChanged();
    #endregion
		
		public Progettisti()
		{
			this._Interessi = new EntitySet<Interessi>(new Action<Interessi>(this.attach_Interessi), new Action<Interessi>(this.detach_Interessi));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this.OnCodiceChanging(value);
					this.SendPropertyChanging();
					this._Codice = value;
					this.SendPropertyChanged("Codice");
					this.OnCodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuogoNascita", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LuogoNascita
		{
			get
			{
				return this._LuogoNascita;
			}
			set
			{
				if ((this._LuogoNascita != value))
				{
					this.OnLuogoNascitaChanging(value);
					this.SendPropertyChanging();
					this._LuogoNascita = value;
					this.SendPropertyChanged("LuogoNascita");
					this.OnLuogoNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residenza", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Residenza
		{
			get
			{
				return this._Residenza;
			}
			set
			{
				if ((this._Residenza != value))
				{
					this.OnResidenzaChanging(value);
					this.SendPropertyChanging();
					this._Residenza = value;
					this.SendPropertyChanged("Residenza");
					this.OnResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stipendio", DbType="Real NOT NULL")]
		public float Stipendio
		{
			get
			{
				return this._Stipendio;
			}
			set
			{
				if ((this._Stipendio != value))
				{
					this.OnStipendioChanging(value);
					this.SendPropertyChanging();
					this._Stipendio = value;
					this.SendPropertyChanged("Stipendio");
					this.OnStipendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Progettisti_Interessi", Storage="_Interessi", ThisKey="Codice", OtherKey="CodiceProgettista")]
		public EntitySet<Interessi> Interessi
		{
			get
			{
				return this._Interessi;
			}
			set
			{
				this._Interessi.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Progettisti = this;
		}
		
		private void detach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Progettisti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopPNC")]
	public partial class TopPNC
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private System.Nullable<int> _Numero;
		
		public TopPNC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopComponentCode")]
	public partial class TopComponentCode
	{
		
		private decimal _CategoriaProdotto;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private string _NomeComponente;
		
		private System.Nullable<int> _Numero;
		
		public TopComponentCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeComponente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeComponente
		{
			get
			{
				return this._NomeComponente;
			}
			set
			{
				if ((this._NomeComponente != value))
				{
					this._NomeComponente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AvgTime")]
	public partial class AvgTime
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _CodiceTipo;
		
		private string _NomeTipo;
		
		private System.Nullable<decimal> _TempoMedioRiparazione;
		
		public AvgTime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipo", DbType="Decimal(4,0) NOT NULL")]
		public decimal CodiceTipo
		{
			get
			{
				return this._CodiceTipo;
			}
			set
			{
				if ((this._CodiceTipo != value))
				{
					this._CodiceTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeTipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeTipo
		{
			get
			{
				return this._NomeTipo;
			}
			set
			{
				if ((this._NomeTipo != value))
				{
					this._NomeTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoMedioRiparazione", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TempoMedioRiparazione
		{
			get
			{
				return this._TempoMedioRiparazione;
			}
			set
			{
				if ((this._TempoMedioRiparazione != value))
				{
					this._TempoMedioRiparazione = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopCostSpareParts")]
	public partial class TopCostSpareParts
	{
		
		private decimal _CategoriaProdotto;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private System.Nullable<decimal> _CostoTotale;
		
		public TopCostSpareParts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL")]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					this._DataRichiestaIntervento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoTotale", DbType="Money")]
		public System.Nullable<decimal> CostoTotale
		{
			get
			{
				return this._CostoTotale;
			}
			set
			{
				if ((this._CostoTotale != value))
				{
					this._CostoTotale = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopNations")]
	public partial class TopNations
	{
		
		private decimal _CategoriaProdotto;
		
		private string _Nazione;
		
		private System.Nullable<int> ___;
		
		public TopNations()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this._Nazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="___", DbType="Int")]
		public System.Nullable<int> __
		{
			get
			{
				return this.___;
			}
			set
			{
				if ((this.___ != value))
				{
					this.___ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopSpareParts")]
	public partial class TopSpareParts
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _Codice;
		
		private string _Nome;
		
		private decimal _CostoAcquisto;
		
		private decimal _CostoInstallazione;
		
		private System.Nullable<int> _Numero;
		
		public TopSpareParts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(15,0) NOT NULL")]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this._Codice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoAcquisto", DbType="SmallMoney NOT NULL")]
		public decimal CostoAcquisto
		{
			get
			{
				return this._CostoAcquisto;
			}
			set
			{
				if ((this._CostoAcquisto != value))
				{
					this._CostoAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoInstallazione", DbType="SmallMoney NOT NULL")]
		public decimal CostoInstallazione
		{
			get
			{
				return this._CostoInstallazione;
			}
			set
			{
				if ((this._CostoInstallazione != value))
				{
					this._CostoInstallazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTFInstallation")]
	public partial class TTFInstallation
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private System.Nullable<decimal> _CodiceGaranzia;
		
		private string _Modello;
		
		private System.Nullable<int> _TTF_in_giorni;
		
		public TTFInstallation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceGaranzia", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CodiceGaranzia
		{
			get
			{
				return this._CodiceGaranzia;
			}
			set
			{
				if ((this._CodiceGaranzia != value))
				{
					this._CodiceGaranzia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TTF (giorni)]", Storage="_TTF_in_giorni", DbType="Int")]
		public System.Nullable<int> TTF_in_giorni
		{
			get
			{
				return this._TTF_in_giorni;
			}
			set
			{
				if ((this._TTF_in_giorni != value))
				{
					this._TTF_in_giorni = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTFPurchase")]
	public partial class TTFPurchase
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private System.Nullable<decimal> _CodiceGaranzia;
		
		private string _Modello;
		
		private System.Nullable<int> _TTF_in_giorni;
		
		public TTFPurchase()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceGaranzia", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CodiceGaranzia
		{
			get
			{
				return this._CodiceGaranzia;
			}
			set
			{
				if ((this._CodiceGaranzia != value))
				{
					this._CodiceGaranzia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TTF (giorni)]", Storage="_TTF_in_giorni", DbType="Int")]
		public System.Nullable<int> TTF_in_giorni
		{
			get
			{
				return this._TTF_in_giorni;
			}
			set
			{
				if ((this._TTF_in_giorni != value))
				{
					this._TTF_in_giorni = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Interessi")]
	public partial class Interessi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceCategoria;
		
		private decimal _CodiceProgettista;
		
		private EntityRef<Progettisti> _Progettisti;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceCategoriaChanging(decimal value);
    partial void OnCodiceCategoriaChanged();
    partial void OnCodiceProgettistaChanging(decimal value);
    partial void OnCodiceProgettistaChanged();
    #endregion
		
		public Interessi()
		{
			this._Progettisti = default(EntityRef<Progettisti>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceCategoria", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceCategoria
		{
			get
			{
				return this._CodiceCategoria;
			}
			set
			{
				if ((this._CodiceCategoria != value))
				{
					this.OnCodiceCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodiceCategoria = value;
					this.SendPropertyChanged("CodiceCategoria");
					this.OnCodiceCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceProgettista", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceProgettista
		{
			get
			{
				return this._CodiceProgettista;
			}
			set
			{
				if ((this._CodiceProgettista != value))
				{
					if (this._Progettisti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceProgettistaChanging(value);
					this.SendPropertyChanging();
					this._CodiceProgettista = value;
					this.SendPropertyChanged("CodiceProgettista");
					this.OnCodiceProgettistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Progettisti_Interessi", Storage="_Progettisti", ThisKey="CodiceProgettista", OtherKey="Codice", IsForeignKey=true)]
		public Progettisti Progettisti
		{
			get
			{
				return this._Progettisti.Entity;
			}
			set
			{
				Progettisti previousValue = this._Progettisti.Entity;
				if (((previousValue != value) 
							|| (this._Progettisti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Progettisti.Entity = null;
						previousValue.Interessi.Remove(this);
					}
					this._Progettisti.Entity = value;
					if ((value != null))
					{
						value.Interessi.Add(this);
						this._CodiceProgettista = value.Codice;
					}
					else
					{
						this._CodiceProgettista = default(decimal);
					}
					this.SendPropertyChanged("Progettisti");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guasti")]
	public partial class Guasti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NumeroTelefonoCliente;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private string _DescrizioneCliente;
		
		private string _DescrizioneTecnico;
		
		private decimal _CategoriaProdotto;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private System.Nullable<decimal> _CodiceTipoDifetto;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroTelefonoClienteChanging(string value);
    partial void OnNumeroTelefonoClienteChanged();
    partial void OnDataRichiestaInterventoChanging(System.DateTime value);
    partial void OnDataRichiestaInterventoChanged();
    partial void OnPNCChanging(decimal value);
    partial void OnPNCChanged();
    partial void OnSNCChanging(decimal value);
    partial void OnSNCChanged();
    partial void OnDescrizioneClienteChanging(string value);
    partial void OnDescrizioneClienteChanged();
    partial void OnDescrizioneTecnicoChanging(string value);
    partial void OnDescrizioneTecnicoChanged();
    partial void OnCategoriaProdottoChanging(decimal value);
    partial void OnCategoriaProdottoChanged();
    partial void OnComponentCodeChanging(System.Nullable<decimal> value);
    partial void OnComponentCodeChanged();
    partial void OnCodiceTipoDifettoChanging(System.Nullable<decimal> value);
    partial void OnCodiceTipoDifettoChanged();
    #endregion
		
		public Guasti()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTelefonoCliente", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NumeroTelefonoCliente
		{
			get
			{
				return this._NumeroTelefonoCliente;
			}
			set
			{
				if ((this._NumeroTelefonoCliente != value))
				{
					this.OnNumeroTelefonoClienteChanging(value);
					this.SendPropertyChanging();
					this._NumeroTelefonoCliente = value;
					this.SendPropertyChanged("NumeroTelefonoCliente");
					this.OnNumeroTelefonoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					this.OnDataRichiestaInterventoChanging(value);
					this.SendPropertyChanging();
					this._DataRichiestaIntervento = value;
					this.SendPropertyChanged("DataRichiestaIntervento");
					this.OnDataRichiestaInterventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL", IsPrimaryKey=true)]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this.OnPNCChanging(value);
					this.SendPropertyChanging();
					this._PNC = value;
					this.SendPropertyChanged("PNC");
					this.OnPNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL", IsPrimaryKey=true)]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this.OnSNCChanging(value);
					this.SendPropertyChanging();
					this._SNC = value;
					this.SendPropertyChanged("SNC");
					this.OnSNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneCliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DescrizioneCliente
		{
			get
			{
				return this._DescrizioneCliente;
			}
			set
			{
				if ((this._DescrizioneCliente != value))
				{
					this.OnDescrizioneClienteChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneCliente = value;
					this.SendPropertyChanged("DescrizioneCliente");
					this.OnDescrizioneClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneTecnico", DbType="VarChar(100)")]
		public string DescrizioneTecnico
		{
			get
			{
				return this._DescrizioneTecnico;
			}
			set
			{
				if ((this._DescrizioneTecnico != value))
				{
					this.OnDescrizioneTecnicoChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneTecnico = value;
					this.SendPropertyChanged("DescrizioneTecnico");
					this.OnDescrizioneTecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this.OnCategoriaProdottoChanging(value);
					this.SendPropertyChanging();
					this._CategoriaProdotto = value;
					this.SendPropertyChanged("CategoriaProdotto");
					this.OnCategoriaProdottoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this.OnComponentCodeChanging(value);
					this.SendPropertyChanging();
					this._ComponentCode = value;
					this.SendPropertyChanged("ComponentCode");
					this.OnComponentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipoDifetto", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> CodiceTipoDifetto
		{
			get
			{
				return this._CodiceTipoDifetto;
			}
			set
			{
				if ((this._CodiceTipoDifetto != value))
				{
					this.OnCodiceTipoDifettoChanging(value);
					this.SendPropertyChanging();
					this._CodiceTipoDifetto = value;
					this.SendPropertyChanged("CodiceTipoDifetto");
					this.OnCodiceTipoDifettoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
