#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FailuresManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestioneGuasti-2019")]
	public partial class GestioneGuastiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertProgettisti(Progettisti instance);
    partial void UpdateProgettisti(Progettisti instance);
    partial void DeleteProgettisti(Progettisti instance);
    partial void InsertInteressi(Interessi instance);
    partial void UpdateInteressi(Interessi instance);
    partial void DeleteInteressi(Interessi instance);
    partial void InsertGuasti(Guasti instance);
    partial void UpdateGuasti(Guasti instance);
    partial void DeleteGuasti(Guasti instance);
    partial void InsertOperatori(Operatori instance);
    partial void UpdateOperatori(Operatori instance);
    partial void DeleteOperatori(Operatori instance);
    partial void InsertTecnici(Tecnici instance);
    partial void UpdateTecnici(Tecnici instance);
    partial void DeleteTecnici(Tecnici instance);
    partial void InsertInterventi(Interventi instance);
    partial void UpdateInterventi(Interventi instance);
    partial void DeleteInterventi(Interventi instance);
    partial void InsertProdotti(Prodotti instance);
    partial void UpdateProdotti(Prodotti instance);
    partial void DeleteProdotti(Prodotti instance);
    partial void InsertCategorie(Categorie instance);
    partial void UpdateCategorie(Categorie instance);
    partial void DeleteCategorie(Categorie instance);
    #endregion
		
		public GestioneGuastiDataContext() : 
				base(global::FailuresManagement.Properties.Settings.Default.GestioneGuasti_2019ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestioneGuastiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AllFaults> AllFaults
		{
			get
			{
				return this.GetTable<AllFaults>();
			}
		}
		
		public System.Data.Linq.Table<Progettisti> Progettisti
		{
			get
			{
				return this.GetTable<Progettisti>();
			}
		}
		
		public System.Data.Linq.Table<TopPNC> TopPNC
		{
			get
			{
				return this.GetTable<TopPNC>();
			}
		}
		
		public System.Data.Linq.Table<TopComponentCode> TopComponentCode
		{
			get
			{
				return this.GetTable<TopComponentCode>();
			}
		}
		
		public System.Data.Linq.Table<AvgTime> AvgTime
		{
			get
			{
				return this.GetTable<AvgTime>();
			}
		}
		
		public System.Data.Linq.Table<TopCostSpareParts> TopCostSpareParts
		{
			get
			{
				return this.GetTable<TopCostSpareParts>();
			}
		}
		
		public System.Data.Linq.Table<TopNations> TopNations
		{
			get
			{
				return this.GetTable<TopNations>();
			}
		}
		
		public System.Data.Linq.Table<TopSpareParts> TopSpareParts
		{
			get
			{
				return this.GetTable<TopSpareParts>();
			}
		}
		
		public System.Data.Linq.Table<TTFInstallation> TTFInstallation
		{
			get
			{
				return this.GetTable<TTFInstallation>();
			}
		}
		
		public System.Data.Linq.Table<TTFPurchase> TTFPurchase
		{
			get
			{
				return this.GetTable<TTFPurchase>();
			}
		}
		
		public System.Data.Linq.Table<Interessi> Interessi
		{
			get
			{
				return this.GetTable<Interessi>();
			}
		}
		
		public System.Data.Linq.Table<Guasti> Guasti
		{
			get
			{
				return this.GetTable<Guasti>();
			}
		}
		
		public System.Data.Linq.Table<Operatori> Operatori
		{
			get
			{
				return this.GetTable<Operatori>();
			}
		}
		
		public System.Data.Linq.Table<Tecnici> Tecnici
		{
			get
			{
				return this.GetTable<Tecnici>();
			}
		}
		
		public System.Data.Linq.Table<Interventi> Interventi
		{
			get
			{
				return this.GetTable<Interventi>();
			}
		}
		
		public System.Data.Linq.Table<NewInterventions> NewInterventions
		{
			get
			{
				return this.GetTable<NewInterventions>();
			}
		}
		
		public System.Data.Linq.Table<Prodotti> Prodotti
		{
			get
			{
				return this.GetTable<Prodotti>();
			}
		}
		
		public System.Data.Linq.Table<Categorie> Categorie
		{
			get
			{
				return this.GetTable<Categorie>();
			}
		}
		
		public System.Data.Linq.Table<CentersIntervAvg> CentersIntervAvg
		{
			get
			{
				return this.GetTable<CentersIntervAvg>();
			}
		}
		
		public System.Data.Linq.Table<OperatorsIntervCount> OperatorsIntervCount
		{
			get
			{
				return this.GetTable<OperatorsIntervCount>();
			}
		}
		
		public System.Data.Linq.Table<TechniciansIntervCount> TechniciansIntervCount
		{
			get
			{
				return this.GetTable<TechniciansIntervCount>();
			}
		}
		
		public System.Data.Linq.Table<TechniciansIntervAvg> TechniciansIntervAvg
		{
			get
			{
				return this.GetTable<TechniciansIntervAvg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AllFaults")]
	public partial class AllFaults
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private string _Modello;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private System.DateTime _DataVisita;
		
		private System.Nullable<System.DateTime> _DataAcquisto;
		
		private System.Nullable<System.DateTime> _DataInstallazione;
		
		private string _Nazione;
		
		private string _DescrizioneCliente;
		
		private string _DescrizioneTecnico;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private string _NomeComponente;
		
		private System.Nullable<decimal> _CodiceTipoDifetto;
		
		private string _NomeTipoDifetto;
		
		private System.Nullable<decimal> _CodiceRicambio;
		
		private string _NomeRicambio;
		
		private System.Nullable<decimal> _CostoAcquisto;
		
		private System.Nullable<decimal> _CostoInstallazione;
		
		public AllFaults()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL")]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					this._DataRichiestaIntervento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVisita", DbType="DateTime NOT NULL")]
		public System.DateTime DataVisita
		{
			get
			{
				return this._DataVisita;
			}
			set
			{
				if ((this._DataVisita != value))
				{
					this._DataVisita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAcquisto", DbType="Date")]
		public System.Nullable<System.DateTime> DataAcquisto
		{
			get
			{
				return this._DataAcquisto;
			}
			set
			{
				if ((this._DataAcquisto != value))
				{
					this._DataAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInstallazione", DbType="Date")]
		public System.Nullable<System.DateTime> DataInstallazione
		{
			get
			{
				return this._DataInstallazione;
			}
			set
			{
				if ((this._DataInstallazione != value))
				{
					this._DataInstallazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this._Nazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneCliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DescrizioneCliente
		{
			get
			{
				return this._DescrizioneCliente;
			}
			set
			{
				if ((this._DescrizioneCliente != value))
				{
					this._DescrizioneCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneTecnico", DbType="VarChar(100)")]
		public string DescrizioneTecnico
		{
			get
			{
				return this._DescrizioneTecnico;
			}
			set
			{
				if ((this._DescrizioneTecnico != value))
				{
					this._DescrizioneTecnico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeComponente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeComponente
		{
			get
			{
				return this._NomeComponente;
			}
			set
			{
				if ((this._NomeComponente != value))
				{
					this._NomeComponente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipoDifetto", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> CodiceTipoDifetto
		{
			get
			{
				return this._CodiceTipoDifetto;
			}
			set
			{
				if ((this._CodiceTipoDifetto != value))
				{
					this._CodiceTipoDifetto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeTipoDifetto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeTipoDifetto
		{
			get
			{
				return this._NomeTipoDifetto;
			}
			set
			{
				if ((this._NomeTipoDifetto != value))
				{
					this._NomeTipoDifetto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceRicambio", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> CodiceRicambio
		{
			get
			{
				return this._CodiceRicambio;
			}
			set
			{
				if ((this._CodiceRicambio != value))
				{
					this._CodiceRicambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeRicambio", DbType="VarChar(20)")]
		public string NomeRicambio
		{
			get
			{
				return this._NomeRicambio;
			}
			set
			{
				if ((this._NomeRicambio != value))
				{
					this._NomeRicambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoAcquisto", DbType="SmallMoney")]
		public System.Nullable<decimal> CostoAcquisto
		{
			get
			{
				return this._CostoAcquisto;
			}
			set
			{
				if ((this._CostoAcquisto != value))
				{
					this._CostoAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoInstallazione", DbType="SmallMoney")]
		public System.Nullable<decimal> CostoInstallazione
		{
			get
			{
				return this._CostoInstallazione;
			}
			set
			{
				if ((this._CostoInstallazione != value))
				{
					this._CostoInstallazione = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Progettisti")]
	public partial class Progettisti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codice;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private string _LuogoNascita;
		
		private string _Residenza;
		
		private float _Stipendio;
		
		private EntitySet<Interessi> _Interessi;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceChanging(decimal value);
    partial void OnCodiceChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnLuogoNascitaChanging(string value);
    partial void OnLuogoNascitaChanged();
    partial void OnResidenzaChanging(string value);
    partial void OnResidenzaChanged();
    partial void OnStipendioChanging(float value);
    partial void OnStipendioChanged();
    #endregion
		
		public Progettisti()
		{
			this._Interessi = new EntitySet<Interessi>(new Action<Interessi>(this.attach_Interessi), new Action<Interessi>(this.detach_Interessi));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this.OnCodiceChanging(value);
					this.SendPropertyChanging();
					this._Codice = value;
					this.SendPropertyChanged("Codice");
					this.OnCodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuogoNascita", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LuogoNascita
		{
			get
			{
				return this._LuogoNascita;
			}
			set
			{
				if ((this._LuogoNascita != value))
				{
					this.OnLuogoNascitaChanging(value);
					this.SendPropertyChanging();
					this._LuogoNascita = value;
					this.SendPropertyChanged("LuogoNascita");
					this.OnLuogoNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residenza", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Residenza
		{
			get
			{
				return this._Residenza;
			}
			set
			{
				if ((this._Residenza != value))
				{
					this.OnResidenzaChanging(value);
					this.SendPropertyChanging();
					this._Residenza = value;
					this.SendPropertyChanged("Residenza");
					this.OnResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stipendio", DbType="Real NOT NULL")]
		public float Stipendio
		{
			get
			{
				return this._Stipendio;
			}
			set
			{
				if ((this._Stipendio != value))
				{
					this.OnStipendioChanging(value);
					this.SendPropertyChanging();
					this._Stipendio = value;
					this.SendPropertyChanged("Stipendio");
					this.OnStipendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Progettisti_Interessi", Storage="_Interessi", ThisKey="Codice", OtherKey="CodiceProgettista")]
		public EntitySet<Interessi> Interessi
		{
			get
			{
				return this._Interessi;
			}
			set
			{
				this._Interessi.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Progettisti = this;
		}
		
		private void detach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Progettisti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopPNC")]
	public partial class TopPNC
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private System.Nullable<int> _Numero;
		
		public TopPNC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopComponentCode")]
	public partial class TopComponentCode
	{
		
		private decimal _CategoriaProdotto;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private string _NomeComponente;
		
		private System.Nullable<int> _Numero;
		
		public TopComponentCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeComponente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeComponente
		{
			get
			{
				return this._NomeComponente;
			}
			set
			{
				if ((this._NomeComponente != value))
				{
					this._NomeComponente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AvgTime")]
	public partial class AvgTime
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _CodiceTipo;
		
		private string _NomeTipo;
		
		private System.Nullable<decimal> _TempoMedioRiparazione;
		
		public AvgTime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipo", DbType="Decimal(4,0) NOT NULL")]
		public decimal CodiceTipo
		{
			get
			{
				return this._CodiceTipo;
			}
			set
			{
				if ((this._CodiceTipo != value))
				{
					this._CodiceTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeTipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomeTipo
		{
			get
			{
				return this._NomeTipo;
			}
			set
			{
				if ((this._NomeTipo != value))
				{
					this._NomeTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoMedioRiparazione", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TempoMedioRiparazione
		{
			get
			{
				return this._TempoMedioRiparazione;
			}
			set
			{
				if ((this._TempoMedioRiparazione != value))
				{
					this._TempoMedioRiparazione = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopCostSpareParts")]
	public partial class TopCostSpareParts
	{
		
		private decimal _CategoriaProdotto;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private System.Nullable<decimal> _CostoTotale;
		
		public TopCostSpareParts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL")]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					this._DataRichiestaIntervento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoTotale", DbType="Money")]
		public System.Nullable<decimal> CostoTotale
		{
			get
			{
				return this._CostoTotale;
			}
			set
			{
				if ((this._CostoTotale != value))
				{
					this._CostoTotale = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopNations")]
	public partial class TopNations
	{
		
		private decimal _CategoriaProdotto;
		
		private string _Nazione;
		
		private System.Nullable<int> ___;
		
		public TopNations()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this._Nazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="___", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this.___;
			}
			set
			{
				if ((this.___ != value))
				{
					this.___ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopSpareParts")]
	public partial class TopSpareParts
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _Codice;
		
		private string _Nome;
		
		private decimal _CostoAcquisto;
		
		private decimal _CostoInstallazione;
		
		private System.Nullable<int> _Numero;
		
		public TopSpareParts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(15,0) NOT NULL")]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this._Codice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoAcquisto", DbType="SmallMoney NOT NULL")]
		public decimal CostoAcquisto
		{
			get
			{
				return this._CostoAcquisto;
			}
			set
			{
				if ((this._CostoAcquisto != value))
				{
					this._CostoAcquisto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoInstallazione", DbType="SmallMoney NOT NULL")]
		public decimal CostoInstallazione
		{
			get
			{
				return this._CostoInstallazione;
			}
			set
			{
				if ((this._CostoInstallazione != value))
				{
					this._CostoInstallazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTFInstallation")]
	public partial class TTFInstallation
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private System.Nullable<decimal> _CodiceGaranzia;
		
		private string _Modello;
		
		private System.Nullable<int> _TTF_in_giorni;
		
		public TTFInstallation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceGaranzia", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CodiceGaranzia
		{
			get
			{
				return this._CodiceGaranzia;
			}
			set
			{
				if ((this._CodiceGaranzia != value))
				{
					this._CodiceGaranzia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TTF (giorni)]", Storage="_TTF_in_giorni", DbType="Int")]
		public System.Nullable<int> TTF_in_giorni
		{
			get
			{
				return this._TTF_in_giorni;
			}
			set
			{
				if ((this._TTF_in_giorni != value))
				{
					this._TTF_in_giorni = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTFPurchase")]
	public partial class TTFPurchase
	{
		
		private decimal _CategoriaProdotto;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private System.Nullable<decimal> _CodiceGaranzia;
		
		private string _Modello;
		
		private System.Nullable<int> _TTF_in_giorni;
		
		public TTFPurchase()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this._CategoriaProdotto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL")]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this._PNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL")]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this._SNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceGaranzia", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CodiceGaranzia
		{
			get
			{
				return this._CodiceGaranzia;
			}
			set
			{
				if ((this._CodiceGaranzia != value))
				{
					this._CodiceGaranzia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this._Modello = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TTF (giorni)]", Storage="_TTF_in_giorni", DbType="Int")]
		public System.Nullable<int> TTF_in_giorni
		{
			get
			{
				return this._TTF_in_giorni;
			}
			set
			{
				if ((this._TTF_in_giorni != value))
				{
					this._TTF_in_giorni = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Interessi")]
	public partial class Interessi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CodiceCategoria;
		
		private decimal _CodiceProgettista;
		
		private EntityRef<Progettisti> _Progettisti;
		
		private EntityRef<Categorie> _Categorie;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceCategoriaChanging(decimal value);
    partial void OnCodiceCategoriaChanged();
    partial void OnCodiceProgettistaChanging(decimal value);
    partial void OnCodiceProgettistaChanged();
    #endregion
		
		public Interessi()
		{
			this._Progettisti = default(EntityRef<Progettisti>);
			this._Categorie = default(EntityRef<Categorie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceCategoria", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceCategoria
		{
			get
			{
				return this._CodiceCategoria;
			}
			set
			{
				if ((this._CodiceCategoria != value))
				{
					if (this._Categorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodiceCategoria = value;
					this.SendPropertyChanged("CodiceCategoria");
					this.OnCodiceCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceProgettista", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CodiceProgettista
		{
			get
			{
				return this._CodiceProgettista;
			}
			set
			{
				if ((this._CodiceProgettista != value))
				{
					if (this._Progettisti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceProgettistaChanging(value);
					this.SendPropertyChanging();
					this._CodiceProgettista = value;
					this.SendPropertyChanged("CodiceProgettista");
					this.OnCodiceProgettistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Progettisti_Interessi", Storage="_Progettisti", ThisKey="CodiceProgettista", OtherKey="Codice", IsForeignKey=true)]
		public Progettisti Progettisti
		{
			get
			{
				return this._Progettisti.Entity;
			}
			set
			{
				Progettisti previousValue = this._Progettisti.Entity;
				if (((previousValue != value) 
							|| (this._Progettisti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Progettisti.Entity = null;
						previousValue.Interessi.Remove(this);
					}
					this._Progettisti.Entity = value;
					if ((value != null))
					{
						value.Interessi.Add(this);
						this._CodiceProgettista = value.Codice;
					}
					else
					{
						this._CodiceProgettista = default(decimal);
					}
					this.SendPropertyChanged("Progettisti");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Interessi", Storage="_Categorie", ThisKey="CodiceCategoria", OtherKey="Codice", IsForeignKey=true)]
		public Categorie Categorie
		{
			get
			{
				return this._Categorie.Entity;
			}
			set
			{
				Categorie previousValue = this._Categorie.Entity;
				if (((previousValue != value) 
							|| (this._Categorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorie.Entity = null;
						previousValue.Interessi.Remove(this);
					}
					this._Categorie.Entity = value;
					if ((value != null))
					{
						value.Interessi.Add(this);
						this._CodiceCategoria = value.Codice;
					}
					else
					{
						this._CodiceCategoria = default(decimal);
					}
					this.SendPropertyChanged("Categorie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guasti")]
	public partial class Guasti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NumeroTelefonoCliente;
		
		private System.DateTime _DataRichiestaIntervento;
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private string _DescrizioneCliente;
		
		private string _DescrizioneTecnico;
		
		private decimal _CategoriaProdotto;
		
		private System.Nullable<decimal> _ComponentCode;
		
		private System.Nullable<decimal> _CodiceTipoDifetto;
		
		private EntityRef<Interventi> _Interventi;
		
		private EntityRef<Prodotti> _Prodotti;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroTelefonoClienteChanging(string value);
    partial void OnNumeroTelefonoClienteChanged();
    partial void OnDataRichiestaInterventoChanging(System.DateTime value);
    partial void OnDataRichiestaInterventoChanged();
    partial void OnPNCChanging(decimal value);
    partial void OnPNCChanged();
    partial void OnSNCChanging(decimal value);
    partial void OnSNCChanged();
    partial void OnDescrizioneClienteChanging(string value);
    partial void OnDescrizioneClienteChanged();
    partial void OnDescrizioneTecnicoChanging(string value);
    partial void OnDescrizioneTecnicoChanged();
    partial void OnCategoriaProdottoChanging(decimal value);
    partial void OnCategoriaProdottoChanged();
    partial void OnComponentCodeChanging(System.Nullable<decimal> value);
    partial void OnComponentCodeChanged();
    partial void OnCodiceTipoDifettoChanging(System.Nullable<decimal> value);
    partial void OnCodiceTipoDifettoChanged();
    #endregion
		
		public Guasti()
		{
			this._Interventi = default(EntityRef<Interventi>);
			this._Prodotti = default(EntityRef<Prodotti>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTelefonoCliente", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NumeroTelefonoCliente
		{
			get
			{
				return this._NumeroTelefonoCliente;
			}
			set
			{
				if ((this._NumeroTelefonoCliente != value))
				{
					if (this._Interventi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNumeroTelefonoClienteChanging(value);
					this.SendPropertyChanging();
					this._NumeroTelefonoCliente = value;
					this.SendPropertyChanged("NumeroTelefonoCliente");
					this.OnNumeroTelefonoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiestaIntervento", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DataRichiestaIntervento
		{
			get
			{
				return this._DataRichiestaIntervento;
			}
			set
			{
				if ((this._DataRichiestaIntervento != value))
				{
					if (this._Interventi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDataRichiestaInterventoChanging(value);
					this.SendPropertyChanging();
					this._DataRichiestaIntervento = value;
					this.SendPropertyChanged("DataRichiestaIntervento");
					this.OnDataRichiestaInterventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL", IsPrimaryKey=true)]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					if (this._Prodotti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPNCChanging(value);
					this.SendPropertyChanging();
					this._PNC = value;
					this.SendPropertyChanged("PNC");
					this.OnPNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL", IsPrimaryKey=true)]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					if (this._Prodotti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSNCChanging(value);
					this.SendPropertyChanging();
					this._SNC = value;
					this.SendPropertyChanged("SNC");
					this.OnSNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneCliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DescrizioneCliente
		{
			get
			{
				return this._DescrizioneCliente;
			}
			set
			{
				if ((this._DescrizioneCliente != value))
				{
					this.OnDescrizioneClienteChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneCliente = value;
					this.SendPropertyChanged("DescrizioneCliente");
					this.OnDescrizioneClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescrizioneTecnico", DbType="VarChar(100)")]
		public string DescrizioneTecnico
		{
			get
			{
				return this._DescrizioneTecnico;
			}
			set
			{
				if ((this._DescrizioneTecnico != value))
				{
					this.OnDescrizioneTecnicoChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneTecnico = value;
					this.SendPropertyChanged("DescrizioneTecnico");
					this.OnDescrizioneTecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaProdotto", DbType="Decimal(2,0) NOT NULL")]
		public decimal CategoriaProdotto
		{
			get
			{
				return this._CategoriaProdotto;
			}
			set
			{
				if ((this._CategoriaProdotto != value))
				{
					this.OnCategoriaProdottoChanging(value);
					this.SendPropertyChanging();
					this._CategoriaProdotto = value;
					this.SendPropertyChanged("CategoriaProdotto");
					this.OnCategoriaProdottoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this.OnComponentCodeChanging(value);
					this.SendPropertyChanging();
					this._ComponentCode = value;
					this.SendPropertyChanged("ComponentCode");
					this.OnComponentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTipoDifetto", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> CodiceTipoDifetto
		{
			get
			{
				return this._CodiceTipoDifetto;
			}
			set
			{
				if ((this._CodiceTipoDifetto != value))
				{
					this.OnCodiceTipoDifettoChanging(value);
					this.SendPropertyChanging();
					this._CodiceTipoDifetto = value;
					this.SendPropertyChanged("CodiceTipoDifetto");
					this.OnCodiceTipoDifettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Interventi_Guasti", Storage="_Interventi", ThisKey="NumeroTelefonoCliente,DataRichiestaIntervento", OtherKey="NumeroTelefonoCliente,DataRichiesta", IsForeignKey=true)]
		public Interventi Interventi
		{
			get
			{
				return this._Interventi.Entity;
			}
			set
			{
				Interventi previousValue = this._Interventi.Entity;
				if (((previousValue != value) 
							|| (this._Interventi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Interventi.Entity = null;
						previousValue.Guasti.Remove(this);
					}
					this._Interventi.Entity = value;
					if ((value != null))
					{
						value.Guasti.Add(this);
						this._NumeroTelefonoCliente = value.NumeroTelefonoCliente;
						this._DataRichiestaIntervento = value.DataRichiesta;
					}
					else
					{
						this._NumeroTelefonoCliente = default(string);
						this._DataRichiestaIntervento = default(System.DateTime);
					}
					this.SendPropertyChanged("Interventi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodotti_Guasti", Storage="_Prodotti", ThisKey="PNC,SNC", OtherKey="PNC,SNC", IsForeignKey=true)]
		public Prodotti Prodotti
		{
			get
			{
				return this._Prodotti.Entity;
			}
			set
			{
				Prodotti previousValue = this._Prodotti.Entity;
				if (((previousValue != value) 
							|| (this._Prodotti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prodotti.Entity = null;
						previousValue.Guasti.Remove(this);
					}
					this._Prodotti.Entity = value;
					if ((value != null))
					{
						value.Guasti.Add(this);
						this._PNC = value.PNC;
						this._SNC = value.SNC;
					}
					else
					{
						this._PNC = default(decimal);
						this._SNC = default(decimal);
					}
					this.SendPropertyChanged("Prodotti");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Operatori")]
	public partial class Operatori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codice;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private string _LuogoNascita;
		
		private string _Residenza;
		
		private float _Stipendio;
		
		private decimal _CodiceNazionaleCentro;
		
		private string _NazioneCentro;
		
		private EntitySet<Interventi> _Interventi;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceChanging(decimal value);
    partial void OnCodiceChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnLuogoNascitaChanging(string value);
    partial void OnLuogoNascitaChanged();
    partial void OnResidenzaChanging(string value);
    partial void OnResidenzaChanged();
    partial void OnStipendioChanging(float value);
    partial void OnStipendioChanged();
    partial void OnCodiceNazionaleCentroChanging(decimal value);
    partial void OnCodiceNazionaleCentroChanged();
    partial void OnNazioneCentroChanging(string value);
    partial void OnNazioneCentroChanged();
    #endregion
		
		public Operatori()
		{
			this._Interventi = new EntitySet<Interventi>(new Action<Interventi>(this.attach_Interventi), new Action<Interventi>(this.detach_Interventi));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this.OnCodiceChanging(value);
					this.SendPropertyChanging();
					this._Codice = value;
					this.SendPropertyChanged("Codice");
					this.OnCodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuogoNascita", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LuogoNascita
		{
			get
			{
				return this._LuogoNascita;
			}
			set
			{
				if ((this._LuogoNascita != value))
				{
					this.OnLuogoNascitaChanging(value);
					this.SendPropertyChanging();
					this._LuogoNascita = value;
					this.SendPropertyChanged("LuogoNascita");
					this.OnLuogoNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residenza", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Residenza
		{
			get
			{
				return this._Residenza;
			}
			set
			{
				if ((this._Residenza != value))
				{
					this.OnResidenzaChanging(value);
					this.SendPropertyChanging();
					this._Residenza = value;
					this.SendPropertyChanged("Residenza");
					this.OnResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stipendio", DbType="Real NOT NULL")]
		public float Stipendio
		{
			get
			{
				return this._Stipendio;
			}
			set
			{
				if ((this._Stipendio != value))
				{
					this.OnStipendioChanging(value);
					this.SendPropertyChanging();
					this._Stipendio = value;
					this.SendPropertyChanged("Stipendio");
					this.OnStipendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceNazionaleCentro", DbType="Decimal(3,0) NOT NULL")]
		public decimal CodiceNazionaleCentro
		{
			get
			{
				return this._CodiceNazionaleCentro;
			}
			set
			{
				if ((this._CodiceNazionaleCentro != value))
				{
					this.OnCodiceNazionaleCentroChanging(value);
					this.SendPropertyChanging();
					this._CodiceNazionaleCentro = value;
					this.SendPropertyChanged("CodiceNazionaleCentro");
					this.OnCodiceNazionaleCentroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazioneCentro", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string NazioneCentro
		{
			get
			{
				return this._NazioneCentro;
			}
			set
			{
				if ((this._NazioneCentro != value))
				{
					this.OnNazioneCentroChanging(value);
					this.SendPropertyChanging();
					this._NazioneCentro = value;
					this.SendPropertyChanged("NazioneCentro");
					this.OnNazioneCentroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Operatori_Interventi", Storage="_Interventi", ThisKey="Codice", OtherKey="CodiceOperatore")]
		public EntitySet<Interventi> Interventi
		{
			get
			{
				return this._Interventi;
			}
			set
			{
				this._Interventi.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Interventi(Interventi entity)
		{
			this.SendPropertyChanging();
			entity.Operatori = this;
		}
		
		private void detach_Interventi(Interventi entity)
		{
			this.SendPropertyChanging();
			entity.Operatori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tecnici")]
	public partial class Tecnici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codice;
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private string _LuogoNascita;
		
		private string _Residenza;
		
		private float _Stipendio;
		
		private bool _DipendenteInterno;
		
		private decimal _CodiceNazionaleCentro;
		
		private string _NazioneCentro;
		
		private EntitySet<Interventi> _Interventi;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceChanging(decimal value);
    partial void OnCodiceChanged();
    partial void OnCFChanging(string value);
    partial void OnCFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnLuogoNascitaChanging(string value);
    partial void OnLuogoNascitaChanged();
    partial void OnResidenzaChanging(string value);
    partial void OnResidenzaChanged();
    partial void OnStipendioChanging(float value);
    partial void OnStipendioChanged();
    partial void OnDipendenteInternoChanging(bool value);
    partial void OnDipendenteInternoChanged();
    partial void OnCodiceNazionaleCentroChanging(decimal value);
    partial void OnCodiceNazionaleCentroChanged();
    partial void OnNazioneCentroChanging(string value);
    partial void OnNazioneCentroChanged();
    #endregion
		
		public Tecnici()
		{
			this._Interventi = new EntitySet<Interventi>(new Action<Interventi>(this.attach_Interventi), new Action<Interventi>(this.detach_Interventi));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(6,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this.OnCodiceChanging(value);
					this.SendPropertyChanging();
					this._Codice = value;
					this.SendPropertyChanged("Codice");
					this.OnCodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this.OnCFChanging(value);
					this.SendPropertyChanging();
					this._CF = value;
					this.SendPropertyChanged("CF");
					this.OnCFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuogoNascita", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LuogoNascita
		{
			get
			{
				return this._LuogoNascita;
			}
			set
			{
				if ((this._LuogoNascita != value))
				{
					this.OnLuogoNascitaChanging(value);
					this.SendPropertyChanging();
					this._LuogoNascita = value;
					this.SendPropertyChanged("LuogoNascita");
					this.OnLuogoNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residenza", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Residenza
		{
			get
			{
				return this._Residenza;
			}
			set
			{
				if ((this._Residenza != value))
				{
					this.OnResidenzaChanging(value);
					this.SendPropertyChanging();
					this._Residenza = value;
					this.SendPropertyChanged("Residenza");
					this.OnResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stipendio", DbType="Real NOT NULL")]
		public float Stipendio
		{
			get
			{
				return this._Stipendio;
			}
			set
			{
				if ((this._Stipendio != value))
				{
					this.OnStipendioChanging(value);
					this.SendPropertyChanging();
					this._Stipendio = value;
					this.SendPropertyChanged("Stipendio");
					this.OnStipendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DipendenteInterno", DbType="Bit NOT NULL")]
		public bool DipendenteInterno
		{
			get
			{
				return this._DipendenteInterno;
			}
			set
			{
				if ((this._DipendenteInterno != value))
				{
					this.OnDipendenteInternoChanging(value);
					this.SendPropertyChanging();
					this._DipendenteInterno = value;
					this.SendPropertyChanged("DipendenteInterno");
					this.OnDipendenteInternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceNazionaleCentro", DbType="Decimal(3,0) NOT NULL")]
		public decimal CodiceNazionaleCentro
		{
			get
			{
				return this._CodiceNazionaleCentro;
			}
			set
			{
				if ((this._CodiceNazionaleCentro != value))
				{
					this.OnCodiceNazionaleCentroChanging(value);
					this.SendPropertyChanging();
					this._CodiceNazionaleCentro = value;
					this.SendPropertyChanged("CodiceNazionaleCentro");
					this.OnCodiceNazionaleCentroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazioneCentro", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string NazioneCentro
		{
			get
			{
				return this._NazioneCentro;
			}
			set
			{
				if ((this._NazioneCentro != value))
				{
					this.OnNazioneCentroChanging(value);
					this.SendPropertyChanging();
					this._NazioneCentro = value;
					this.SendPropertyChanged("NazioneCentro");
					this.OnNazioneCentroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tecnici_Interventi", Storage="_Interventi", ThisKey="Codice", OtherKey="CodiceTecnico")]
		public EntitySet<Interventi> Interventi
		{
			get
			{
				return this._Interventi;
			}
			set
			{
				this._Interventi.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Interventi(Interventi entity)
		{
			this.SendPropertyChanging();
			entity.Tecnici = this;
		}
		
		private void detach_Interventi(Interventi entity)
		{
			this.SendPropertyChanging();
			entity.Tecnici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Interventi")]
	public partial class Interventi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NumeroTelefonoCliente;
		
		private System.DateTime _DataRichiesta;
		
		private char _Stato;
		
		private System.DateTime _DataVisita;
		
		private System.Nullable<decimal> _TempoImpiegato;
		
		private string _Nazione;
		
		private decimal _CodiceOperatore;
		
		private System.Nullable<decimal> _CodiceTecnico;
		
		private EntitySet<Guasti> _Guasti;
		
		private EntityRef<Operatori> _Operatori;
		
		private EntityRef<Tecnici> _Tecnici;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroTelefonoClienteChanging(string value);
    partial void OnNumeroTelefonoClienteChanged();
    partial void OnDataRichiestaChanging(System.DateTime value);
    partial void OnDataRichiestaChanged();
    partial void OnStatoChanging(char value);
    partial void OnStatoChanged();
    partial void OnDataVisitaChanging(System.DateTime value);
    partial void OnDataVisitaChanged();
    partial void OnTempoImpiegatoChanging(System.Nullable<decimal> value);
    partial void OnTempoImpiegatoChanged();
    partial void OnNazioneChanging(string value);
    partial void OnNazioneChanged();
    partial void OnCodiceOperatoreChanging(decimal value);
    partial void OnCodiceOperatoreChanged();
    partial void OnCodiceTecnicoChanging(System.Nullable<decimal> value);
    partial void OnCodiceTecnicoChanged();
    #endregion
		
		public Interventi()
		{
			this._Guasti = new EntitySet<Guasti>(new Action<Guasti>(this.attach_Guasti), new Action<Guasti>(this.detach_Guasti));
			this._Operatori = default(EntityRef<Operatori>);
			this._Tecnici = default(EntityRef<Tecnici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTelefonoCliente", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NumeroTelefonoCliente
		{
			get
			{
				return this._NumeroTelefonoCliente;
			}
			set
			{
				if ((this._NumeroTelefonoCliente != value))
				{
					this.OnNumeroTelefonoClienteChanging(value);
					this.SendPropertyChanging();
					this._NumeroTelefonoCliente = value;
					this.SendPropertyChanged("NumeroTelefonoCliente");
					this.OnNumeroTelefonoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiesta", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DataRichiesta
		{
			get
			{
				return this._DataRichiesta;
			}
			set
			{
				if ((this._DataRichiesta != value))
				{
					this.OnDataRichiestaChanging(value);
					this.SendPropertyChanging();
					this._DataRichiesta = value;
					this.SendPropertyChanged("DataRichiesta");
					this.OnDataRichiestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stato", DbType="Char(1) NOT NULL")]
		public char Stato
		{
			get
			{
				return this._Stato;
			}
			set
			{
				if ((this._Stato != value))
				{
					this.OnStatoChanging(value);
					this.SendPropertyChanging();
					this._Stato = value;
					this.SendPropertyChanged("Stato");
					this.OnStatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVisita", DbType="DateTime NOT NULL")]
		public System.DateTime DataVisita
		{
			get
			{
				return this._DataVisita;
			}
			set
			{
				if ((this._DataVisita != value))
				{
					this.OnDataVisitaChanging(value);
					this.SendPropertyChanging();
					this._DataVisita = value;
					this.SendPropertyChanged("DataVisita");
					this.OnDataVisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoImpiegato", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> TempoImpiegato
		{
			get
			{
				return this._TempoImpiegato;
			}
			set
			{
				if ((this._TempoImpiegato != value))
				{
					this.OnTempoImpiegatoChanging(value);
					this.SendPropertyChanging();
					this._TempoImpiegato = value;
					this.SendPropertyChanged("TempoImpiegato");
					this.OnTempoImpiegatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this.OnNazioneChanging(value);
					this.SendPropertyChanging();
					this._Nazione = value;
					this.SendPropertyChanged("Nazione");
					this.OnNazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceOperatore", DbType="Decimal(6,0) NOT NULL")]
		public decimal CodiceOperatore
		{
			get
			{
				return this._CodiceOperatore;
			}
			set
			{
				if ((this._CodiceOperatore != value))
				{
					if (this._Operatori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceOperatoreChanging(value);
					this.SendPropertyChanging();
					this._CodiceOperatore = value;
					this.SendPropertyChanged("CodiceOperatore");
					this.OnCodiceOperatoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceTecnico", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> CodiceTecnico
		{
			get
			{
				return this._CodiceTecnico;
			}
			set
			{
				if ((this._CodiceTecnico != value))
				{
					if (this._Tecnici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceTecnicoChanging(value);
					this.SendPropertyChanging();
					this._CodiceTecnico = value;
					this.SendPropertyChanged("CodiceTecnico");
					this.OnCodiceTecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Interventi_Guasti", Storage="_Guasti", ThisKey="NumeroTelefonoCliente,DataRichiesta", OtherKey="NumeroTelefonoCliente,DataRichiestaIntervento")]
		public EntitySet<Guasti> Guasti
		{
			get
			{
				return this._Guasti;
			}
			set
			{
				this._Guasti.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Operatori_Interventi", Storage="_Operatori", ThisKey="CodiceOperatore", OtherKey="Codice", IsForeignKey=true)]
		public Operatori Operatori
		{
			get
			{
				return this._Operatori.Entity;
			}
			set
			{
				Operatori previousValue = this._Operatori.Entity;
				if (((previousValue != value) 
							|| (this._Operatori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Operatori.Entity = null;
						previousValue.Interventi.Remove(this);
					}
					this._Operatori.Entity = value;
					if ((value != null))
					{
						value.Interventi.Add(this);
						this._CodiceOperatore = value.Codice;
					}
					else
					{
						this._CodiceOperatore = default(decimal);
					}
					this.SendPropertyChanged("Operatori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tecnici_Interventi", Storage="_Tecnici", ThisKey="CodiceTecnico", OtherKey="Codice", IsForeignKey=true)]
		public Tecnici Tecnici
		{
			get
			{
				return this._Tecnici.Entity;
			}
			set
			{
				Tecnici previousValue = this._Tecnici.Entity;
				if (((previousValue != value) 
							|| (this._Tecnici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tecnici.Entity = null;
						previousValue.Interventi.Remove(this);
					}
					this._Tecnici.Entity = value;
					if ((value != null))
					{
						value.Interventi.Add(this);
						this._CodiceTecnico = value.Codice;
					}
					else
					{
						this._CodiceTecnico = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("Tecnici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Guasti(Guasti entity)
		{
			this.SendPropertyChanging();
			entity.Interventi = this;
		}
		
		private void detach_Guasti(Guasti entity)
		{
			this.SendPropertyChanging();
			entity.Interventi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewInterventions")]
	public partial class NewInterventions
	{
		
		private string _NumeroTelefonoCliente;
		
		private System.DateTime _DataRichiesta;
		
		public NewInterventions()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTelefonoCliente", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NumeroTelefonoCliente
		{
			get
			{
				return this._NumeroTelefonoCliente;
			}
			set
			{
				if ((this._NumeroTelefonoCliente != value))
				{
					this._NumeroTelefonoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiesta", DbType="DateTime NOT NULL")]
		public System.DateTime DataRichiesta
		{
			get
			{
				return this._DataRichiesta;
			}
			set
			{
				if ((this._DataRichiesta != value))
				{
					this._DataRichiesta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prodotti")]
	public partial class Prodotti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _PNC;
		
		private decimal _SNC;
		
		private string _Modello;
		
		private System.Nullable<System.DateTime> _DataAcquisto;
		
		private System.Nullable<System.DateTime> _DataInstallazione;
		
		private System.Nullable<decimal> _CodiceGaranzia;
		
		private decimal _CodiceCategoria;
		
		private EntitySet<Guasti> _Guasti;
		
		private EntityRef<Categorie> _Categorie;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPNCChanging(decimal value);
    partial void OnPNCChanged();
    partial void OnSNCChanging(decimal value);
    partial void OnSNCChanged();
    partial void OnModelloChanging(string value);
    partial void OnModelloChanged();
    partial void OnDataAcquistoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataAcquistoChanged();
    partial void OnDataInstallazioneChanging(System.Nullable<System.DateTime> value);
    partial void OnDataInstallazioneChanged();
    partial void OnCodiceGaranziaChanging(System.Nullable<decimal> value);
    partial void OnCodiceGaranziaChanged();
    partial void OnCodiceCategoriaChanging(decimal value);
    partial void OnCodiceCategoriaChanged();
    #endregion
		
		public Prodotti()
		{
			this._Guasti = new EntitySet<Guasti>(new Action<Guasti>(this.attach_Guasti), new Action<Guasti>(this.detach_Guasti));
			this._Categorie = default(EntityRef<Categorie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNC", DbType="Decimal(11,0) NOT NULL", IsPrimaryKey=true)]
		public decimal PNC
		{
			get
			{
				return this._PNC;
			}
			set
			{
				if ((this._PNC != value))
				{
					this.OnPNCChanging(value);
					this.SendPropertyChanging();
					this._PNC = value;
					this.SendPropertyChanged("PNC");
					this.OnPNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNC", DbType="Decimal(8,0) NOT NULL", IsPrimaryKey=true)]
		public decimal SNC
		{
			get
			{
				return this._SNC;
			}
			set
			{
				if ((this._SNC != value))
				{
					this.OnSNCChanging(value);
					this.SendPropertyChanging();
					this._SNC = value;
					this.SendPropertyChanged("SNC");
					this.OnSNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modello", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Modello
		{
			get
			{
				return this._Modello;
			}
			set
			{
				if ((this._Modello != value))
				{
					this.OnModelloChanging(value);
					this.SendPropertyChanging();
					this._Modello = value;
					this.SendPropertyChanged("Modello");
					this.OnModelloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAcquisto", DbType="Date")]
		public System.Nullable<System.DateTime> DataAcquisto
		{
			get
			{
				return this._DataAcquisto;
			}
			set
			{
				if ((this._DataAcquisto != value))
				{
					this.OnDataAcquistoChanging(value);
					this.SendPropertyChanging();
					this._DataAcquisto = value;
					this.SendPropertyChanged("DataAcquisto");
					this.OnDataAcquistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInstallazione", DbType="Date")]
		public System.Nullable<System.DateTime> DataInstallazione
		{
			get
			{
				return this._DataInstallazione;
			}
			set
			{
				if ((this._DataInstallazione != value))
				{
					this.OnDataInstallazioneChanging(value);
					this.SendPropertyChanging();
					this._DataInstallazione = value;
					this.SendPropertyChanged("DataInstallazione");
					this.OnDataInstallazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceGaranzia", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> CodiceGaranzia
		{
			get
			{
				return this._CodiceGaranzia;
			}
			set
			{
				if ((this._CodiceGaranzia != value))
				{
					this.OnCodiceGaranziaChanging(value);
					this.SendPropertyChanging();
					this._CodiceGaranzia = value;
					this.SendPropertyChanged("CodiceGaranzia");
					this.OnCodiceGaranziaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceCategoria", DbType="Decimal(2,0) NOT NULL")]
		public decimal CodiceCategoria
		{
			get
			{
				return this._CodiceCategoria;
			}
			set
			{
				if ((this._CodiceCategoria != value))
				{
					if (this._Categorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodiceCategoria = value;
					this.SendPropertyChanged("CodiceCategoria");
					this.OnCodiceCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prodotti_Guasti", Storage="_Guasti", ThisKey="PNC,SNC", OtherKey="PNC,SNC")]
		public EntitySet<Guasti> Guasti
		{
			get
			{
				return this._Guasti;
			}
			set
			{
				this._Guasti.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Prodotti", Storage="_Categorie", ThisKey="CodiceCategoria", OtherKey="Codice", IsForeignKey=true)]
		public Categorie Categorie
		{
			get
			{
				return this._Categorie.Entity;
			}
			set
			{
				Categorie previousValue = this._Categorie.Entity;
				if (((previousValue != value) 
							|| (this._Categorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorie.Entity = null;
						previousValue.Prodotti.Remove(this);
					}
					this._Categorie.Entity = value;
					if ((value != null))
					{
						value.Prodotti.Add(this);
						this._CodiceCategoria = value.Codice;
					}
					else
					{
						this._CodiceCategoria = default(decimal);
					}
					this.SendPropertyChanged("Categorie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Guasti(Guasti entity)
		{
			this.SendPropertyChanging();
			entity.Prodotti = this;
		}
		
		private void detach_Guasti(Guasti entity)
		{
			this.SendPropertyChanging();
			entity.Prodotti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorie")]
	public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Codice;
		
		private string _Nome;
		
		private EntitySet<Interessi> _Interessi;
		
		private EntitySet<Prodotti> _Prodotti;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceChanging(decimal value);
    partial void OnCodiceChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    #endregion
		
		public Categorie()
		{
			this._Interessi = new EntitySet<Interessi>(new Action<Interessi>(this.attach_Interessi), new Action<Interessi>(this.detach_Interessi));
			this._Prodotti = new EntitySet<Prodotti>(new Action<Prodotti>(this.attach_Prodotti), new Action<Prodotti>(this.detach_Prodotti));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codice", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Codice
		{
			get
			{
				return this._Codice;
			}
			set
			{
				if ((this._Codice != value))
				{
					this.OnCodiceChanging(value);
					this.SendPropertyChanging();
					this._Codice = value;
					this.SendPropertyChanged("Codice");
					this.OnCodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Interessi", Storage="_Interessi", ThisKey="Codice", OtherKey="CodiceCategoria")]
		public EntitySet<Interessi> Interessi
		{
			get
			{
				return this._Interessi;
			}
			set
			{
				this._Interessi.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Prodotti", Storage="_Prodotti", ThisKey="Codice", OtherKey="CodiceCategoria")]
		public EntitySet<Prodotti> Prodotti
		{
			get
			{
				return this._Prodotti;
			}
			set
			{
				this._Prodotti.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = this;
		}
		
		private void detach_Interessi(Interessi entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = null;
		}
		
		private void attach_Prodotti(Prodotti entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = this;
		}
		
		private void detach_Prodotti(Prodotti entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CentersIntervAvg")]
	public partial class CentersIntervAvg
	{
		
		private decimal _CodiceNazionale;
		
		private string _Nazione;
		
		private string _Sede;
		
		private string _AreaCompetenza;
		
		private System.Nullable<double> _TempoMedioRiparazione;
		
		public CentersIntervAvg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceNazionale", DbType="Decimal(3,0) NOT NULL")]
		public decimal CodiceNazionale
		{
			get
			{
				return this._CodiceNazionale;
			}
			set
			{
				if ((this._CodiceNazionale != value))
				{
					this._CodiceNazionale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazione", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Nazione
		{
			get
			{
				return this._Nazione;
			}
			set
			{
				if ((this._Nazione != value))
				{
					this._Nazione = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sede", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Sede
		{
			get
			{
				return this._Sede;
			}
			set
			{
				if ((this._Sede != value))
				{
					this._Sede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaCompetenza", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string AreaCompetenza
		{
			get
			{
				return this._AreaCompetenza;
			}
			set
			{
				if ((this._AreaCompetenza != value))
				{
					this._AreaCompetenza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoMedioRiparazione", DbType="Float")]
		public System.Nullable<double> TempoMedioRiparazione
		{
			get
			{
				return this._TempoMedioRiparazione;
			}
			set
			{
				if ((this._TempoMedioRiparazione != value))
				{
					this._TempoMedioRiparazione = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperatorsIntervCount")]
	public partial class OperatorsIntervCount
	{
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<int> _Numero;
		
		public OperatorsIntervCount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this._CF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this._Cognome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TechniciansIntervCount")]
	public partial class TechniciansIntervCount
	{
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<int> _Numero;
		
		public TechniciansIntervCount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this._CF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this._Cognome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#]", Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TechniciansIntervAvg")]
	public partial class TechniciansIntervAvg
	{
		
		private string _CF;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.Nullable<decimal> _TempoMedioImpiegato;
		
		public TechniciansIntervAvg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CF", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string CF
		{
			get
			{
				return this._CF;
			}
			set
			{
				if ((this._CF != value))
				{
					this._CF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this._Cognome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoMedioImpiegato", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TempoMedioImpiegato
		{
			get
			{
				return this._TempoMedioImpiegato;
			}
			set
			{
				if ((this._TempoMedioImpiegato != value))
				{
					this._TempoMedioImpiegato = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
